version: '3.8'
services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: elearning_db
      MYSQL_USER: user
      MYSQL_PASSWORD: 123456
    ports:
      - "3309:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql